---
connections:
  -
    name: conntest
    user: dbuser
    password: '123'
    host: 192.168.1.81
    database: develop
data:
  default: mysql
  providers:
    -
      name: mysql
      type: ~/lib
      connection: conntest
